// Loads configuration from the embedded JSON, with optional Drive overrides.
// EMBEDDED_FIELD_MAPPINGS / EMBEDDED_RECONCILIATION_TYPES / EMBEDDED_AGENTS /
// EMBEDDED_SETTINGS are defined in 99_Embedded_Config.gs (generated by build.sh).

function getFieldMappings() {
  var override = readJsonFromDriveConfig_('field_mappings.json');
  return override || EMBEDDED_FIELD_MAPPINGS;
}

function getReconciliationTypes() {
  var override = readJsonFromDriveConfig_('reconciliation_types.json');
  return (override || EMBEDDED_RECONCILIATION_TYPES).types;
}

function getReconciliationTypeById(id) {
  var types = getReconciliationTypes();
  for (var i = 0; i < types.length; i++) {
    if (types[i].id === id) return types[i];
  }
  throw new Error('Unknown reconciliation type: ' + id);
}

function getSettings() {
  var sheetSettings = readSettingsFromSheet_();
  var merged = {};
  var k;
  for (k in EMBEDDED_SETTINGS) merged[k] = EMBEDDED_SETTINGS[k];
  for (k in sheetSettings) merged[k] = sheetSettings[k];
  return merged;
}

function getAgentDirectory() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sh = ss.getSheetByName(TAB_AGENTS);
  if (!sh || sh.getLastRow() < 2) {
    // Seed from embedded if Sheet is empty.
    return (EMBEDDED_AGENTS.agents || []).filter(function (a) { return a.active !== false; });
  }
  var range = sh.getRange(1, 1, sh.getLastRow(), sh.getLastColumn()).getValues();
  var header = range[0].map(function (h) { return String(h).trim().toLowerCase(); });
  var col = {};
  for (var i = 0; i < header.length; i++) col[header[i]] = i;
  var out = [];
  for (var r = 1; r < range.length; r++) {
    var row = range[r];
    var name = row[col['name']] && String(row[col['name']]).trim();
    if (!name) continue;
    var active = row[col['active']];
    if (active === false || String(active).toLowerCase() === 'false' || String(active).toLowerCase() === 'no') continue;
    out.push({
      name: name,
      email: row[col['email']] ? String(row[col['email']]).trim() : '',
      branch: row[col['branch']] ? String(row[col['branch']]).trim() : '',
      active: true
    });
  }
  return out;
}

function getAgentEmail(agentName) {
  var dir = getAgentDirectory();
  for (var i = 0; i < dir.length; i++) {
    if (dir[i].name === agentName) return dir[i].email;
  }
  return null;
}

// --- private helpers ---

function readSettingsFromSheet_() {
  var ss = SpreadsheetApp.getActiveSpreadsheet();
  var sh = ss.getSheetByName(TAB_SETTINGS);
  if (!sh || sh.getLastRow() < 2) return {};
  var data = sh.getRange(2, 1, sh.getLastRow() - 1, 2).getValues();
  var out = {};
  for (var i = 0; i < data.length; i++) {
    var k = data[i][0] && String(data[i][0]).trim();
    if (!k) continue;
    var v = data[i][1];
    if (v === '' || v === null || v === undefined) continue;
    if (typeof v === 'string' && /^[0-9]+$/.test(v)) v = Number(v);
    out[k] = v;
  }
  return out;
}

function readJsonFromDriveConfig_(filename) {
  try {
    var settings = EMBEDDED_SETTINGS;
    var folderName = settings.config_folder_name || 'Config';
    var ssFile = DriveApp.getFileById(SpreadsheetApp.getActiveSpreadsheet().getId());
    var parents = ssFile.getParents();
    if (!parents.hasNext()) return null;
    var toolFolder = parents.next();
    var configFolders = toolFolder.getFoldersByName(folderName);
    if (!configFolders.hasNext()) return null;
    var folder = configFolders.next();
    var files = folder.getFilesByName(filename);
    if (!files.hasNext()) return null;
    var f = files.next();
    return JSON.parse(f.getBlob().getDataAsString());
  } catch (e) {
    safeLog('readJsonFromDriveConfig_ failed', { filename: filename, error: String(e) });
    return null;
  }
}
