#!/usr/bin/env bash
# Copies html/ templates and config/ JSON into src/ so clasp can push them.
# Apps Script flattens its project tree at runtime, so all files must live in src/.

set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/src"
HTML="$ROOT/html"
CONFIG="$ROOT/config"

# Clean previously-copied artifacts (leave .gs files untouched)
find "$SRC" -maxdepth 1 -name '*.html' -delete
rm -f "$SRC/99_Embedded_Config.gs"

# Copy HTML templates
if [ -d "$HTML" ]; then
  cp "$HTML"/*.html "$SRC"/
fi

# Embed config JSON into a generated .gs file so it travels with the script.
# Admins can still override at runtime via /Config/field_mappings.json in Drive.
{
  echo "// AUTO-GENERATED by scripts/build.sh — do not edit by hand."
  echo "var EMBEDDED_FIELD_MAPPINGS = $(cat "$CONFIG/field_mappings.json");"
  echo "var EMBEDDED_RECONCILIATION_TYPES = $(cat "$CONFIG/reconciliation_types.json");"
  echo "var EMBEDDED_AGENTS = $(cat "$CONFIG/agents.json");"
  echo "var EMBEDDED_SETTINGS = $(cat "$CONFIG/settings.json");"
  echo "var EMBEDDED_AB_ONLY_RULES = $(cat "$CONFIG/ab_only_rules.json");"
  echo "var EMBEDDED_PLOG_SYNC = $(cat "$CONFIG/plog_sync.json");"
} > "$SRC/99_Embedded_Config.gs"

echo "Build complete. src/ is ready for 'clasp push'."
